#index:
#    path: /
#    controller: App\Controller\DefaultController::index
accueil:
    path: /
    controller: App\Controller\SiteController::index
    
connexion:
    path: /
    controller: App\Controller\SiteController::connection