#index:
#    path: /
#    controller: App\Controller\DefaultController::index
accueil:
    path: /
    controller: App\Controller\SiteController::index
    
connection:
    path: /connection
    controller: App\Controller\SiteController::connection
    
admin:
    path: /admin
    controller: App\Controller\AdminController::index
    
admin_add_chapter:
    path: /admin/add/chapter
    controller: App\Controller\AdminController::addChapter

admin_add_formation:
    path: /admin/add/formation
    controller: App\Controller\AdminController::addFormation
    
admin_add_tutorial:
    path: /admin/add/tutorial
    controller: App\Controller\AdminController::addTutorial
    
admin_delete:
    path: /admin/delete/{id}
    controller: App\Controller\AdminController::delete