#index:
#    path: /
#    controller: App\Controller\DefaultController::index
accueil:
    path: /
    controller: App\Controller\SiteController::index
    
connection:
    path: /connection
    controller: App\Controller\SiteController::connection
    
    